import type { Activity, Asset, Operator, Site } from "./types";

export const initialAssets: Asset[] = [
  {
    id: "CAT-320-014",
    name: "320 GC Excavator",
    category: "Excavator",
    serialNumber: "CAT320GC-8KP014",
    status: "checked-out",
    site: "Northline Expansion",
    location: "Zone 4 · East cut",
    operator: "Marcus Lee",
    operatorInitials: "ML",
    engineHours: 1284,
    idleHours: 186,
    fuelLevel: 68,
    condition: "Good",
    lastActivity: "12 min ago",
  },
  {
    id: "CAT-D6T-022",
    name: "D6T Dozer",
    category: "Dozer",
    serialNumber: "CATD6T-9LQ022",
    status: "available",
    site: "Rental yard",
    location: "Bay 07 · Ready line",
    operator: null,
    operatorInitials: null,
    engineHours: 2198,
    idleHours: 302,
    fuelLevel: 92,
    condition: "Good",
    lastActivity: "Yesterday",
  },
  {
    id: "CAT-950-031",
    name: "950 GC Wheel Loader",
    category: "Wheel loader",
    serialNumber: "CAT950GC-3MS031",
    status: "checked-out",
    site: "Riverbend Materials",
    location: "Crusher pad · South",
    operator: "Daniel Ortiz",
    operatorInitials: "DO",
    engineHours: 882,
    idleHours: 94,
    fuelLevel: 41,
    condition: "Monitor",
    lastActivity: "38 min ago",
  },
  {
    id: "CAT-730-007",
    name: "730 Articulated Truck",
    category: "Haul truck",
    serialNumber: "CAT730-7TR007",
    status: "maintenance",
    site: "Rental yard",
    location: "Service lane · 02",
    operator: null,
    operatorInitials: null,
    engineHours: 3466,
    idleHours: 522,
    fuelLevel: 18,
    condition: "Service due",
    lastActivity: "2 hrs ago",
  },
  {
    id: "CAT-299-018",
    name: "299D3 XE Skid Steer",
    category: "Skid steer",
    serialNumber: "CAT299D3-5AV018",
    status: "checked-out",
    site: "Westport Logistics",
    location: "Dock 3 · Aggregate",
    operator: "Alicia Green",
    operatorInitials: "AG",
    engineHours: 614,
    idleHours: 73,
    fuelLevel: 77,
    condition: "Good",
    lastActivity: "3 hrs ago",
  },
  {
    id: "CAT-259-041",
    name: "259D3 Compact Track Loader",
    category: "Track loader",
    serialNumber: "CAT259D3-2FF041",
    status: "available",
    site: "Rental yard",
    location: "Bay 03 · Wash complete",
    operator: null,
    operatorInitials: null,
    engineHours: 982,
    idleHours: 131,
    fuelLevel: 85,
    condition: "Good",
    lastActivity: "Monday",
  },
];

export const operators: Operator[] = [
  { name: "Marcus Lee", initials: "ML", role: "Northline site operator" },
  { name: "Daniel Ortiz", initials: "DO", role: "Loader operator" },
  { name: "Alicia Green", initials: "AG", role: "Logistics operator" },
  { name: "Priya Nair", initials: "PN", role: "Site supervisor" },
];

export const sites: Site[] = [
  { name: "Northline Expansion", code: "NLE" },
  { name: "Riverbend Materials", code: "RBM" },
  { name: "Westport Logistics", code: "WPL" },
  { name: "Rental yard", code: "YARD" },
];

export const initialActivity: Activity[] = [
  {
    id: "activity-1",
    action: "Telemetry updated",
    assetId: "CAT-320-014",
    assetName: "320 GC Excavator",
    detail: "8.4 engine hrs · 68% fuel",
    time: "12 min ago",
    tone: "blue",
  },
  {
    id: "activity-2",
    action: "Equipment checked out",
    assetId: "CAT-299-018",
    assetName: "299D3 XE Skid Steer",
    detail: "Westport Logistics · Alicia Green",
    time: "3 hrs ago",
    tone: "amber",
  },
  {
    id: "activity-3",
    action: "Condition flagged",
    assetId: "CAT-950-031",
    assetName: "950 GC Wheel Loader",
    detail: "Monitor · fuel below 50%",
    time: "4 hrs ago",
    tone: "red",
  },
  {
    id: "activity-4",
    action: "Asset returned",
    assetId: "CAT-259-041",
    assetName: "259D3 Compact Track Loader",
    detail: "Final condition: Good",
    time: "Yesterday",
    tone: "green",
  },
];
